# Site settings
title: "Nic + Emma"
description: |
    Belleville, Ontario

    August 24, 2019
owner: Nic Durish
first_published: 2019
email: wildy.bus@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.nicandemma.ca"

social:
  github: https://github.com/NicAndEmma/NicAndEmma.Github.io

# Build settings
markdown: kramdown
